// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GymlerLibrary.Models
{
    public partial class FuehrtDurch
    {
        public int Saetze { get; set; }
        public int Wiederholunge { get; set; }
        public decimal Gewichtkg { get; set; }
        public int Id { get; set; }
        public int UebungsId { get; set; }

        public virtual NutzerIn IdNavigation { get; set; }
        public virtual Uebung Uebungs { get; set; }
    }
}