// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GymlerLibrary.Models
{
    public partial class NutzerIn
    {
        public NutzerIn()
        {
            FuehrtDurch = new HashSet<FuehrtDurch>();
            Trainingsplan = new HashSet<Trainingsplan>();
        }

        public int Id { get; set; }
        public string Nutzername { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }

        public virtual ICollection<FuehrtDurch> FuehrtDurch { get; set; }
        public virtual ICollection<Trainingsplan> Trainingsplan { get; set; }
    }
}