// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GymlerLibrary.Models
{
    public partial class Trainingsplan
    {
        public Trainingsplan()
        {
            Uebungs = new HashSet<Uebung>();
        }

        public int PlanId { get; set; }
        public string Titel { get; set; }
        public string Notiz { get; set; }
        public int Id { get; set; }

        public virtual NutzerIn IdNavigation { get; set; }

        public virtual ICollection<Uebung> Uebungs { get; set; }
    }
}