// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GymlerLibrary.Models
{
    public partial class Uebung
    {
        public Uebung()
        {
            FuehrtDurch = new HashSet<FuehrtDurch>();
            Plan = new HashSet<Trainingsplan>();
        }

        public int UebungsId { get; set; }
        public string Bezeichnung { get; set; }
        public string Durchfuehrungsbeschreibung { get; set; }

        public virtual ICollection<FuehrtDurch> FuehrtDurch { get; set; }

        public virtual ICollection<Trainingsplan> Plan { get; set; }
    }
}